### ISSUE TITLE
import apkverify error

### ISSUE THREAD

**Issue by feicong** [shuxin/apk-signature-verify#1]
pkcs7verify could not be import.

```
$ ls
LICENSE		apkfile.py	apkfile.pyc	apkverify.py	apkverify.pyc	pkcs7verify.py	pkcs7verify.pyc
$ python
Python 2.7.14 (default, Mar 14 2018, 16:20:41)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import apkverify
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "apkverify.py", line 12, in <module>
    from pkcs7verify import check_sig, check_sig_v2
  File "pkcs7verify.py", line 425, in <module>
    class TBSCertificate(univ.Sequence):
  File "pkcs7verify.py", line 440, in TBSCertificate
    explicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3)))
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 158, in __init__
    self.__tagToPosMap = self.__computeTagToPosMap()
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 253, in __computeTagToPosMap
    return NamedTypes.PostponedError('Duplicate component tag %s at %s' % (_tagSet, namedType))
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 49, in __repr__
    representation = '%s=%r' % (self.name, self.asn1Object)
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 479, in __repr__
    representation += ' %s=%r' % (attr, value)
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 175, in __repr__
    representation = ', '.join(['%r' % x for x in self.__namedTypes])
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 49, in __repr__
    representation = '%s=%r' % (self.name, self.asn1Object)
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 479, in __repr__
    representation += ' %s=%r' % (attr, value)
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 479, in __repr__
    representation += ' %s=%r' % (attr, value)
  File "pkcs7verify.py", line 306, in __repr__
    if not type:
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 287, in __nonzero__
    return self._value and True or False
  File "/usr/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 199, in plug
    raise error.PyAsn1Error('Attempted "%s" operation on ASN.1 schema object' % name)
pyasn1.error.PyAsn1Error: Attempted "__nonzero__" operation on ASN.1 schema object
>>>
```

**Comment by shuxin** [comment]
use pyasn1=0.1.9

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by feicong** [comment]
thx, it works now.

**Comment by shuxin** [comment]
asn1crypto is easy in use than pyasn1, try my new version.
